WIP refactor: Using compileOnly instead of compile to not include this dependency on time-utils-core library
FAIL: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics